baseURL = "https://tinkerlook.netlify.app"
googleAnalytics = ""
theme = "omega"
title = "TINKER LOOK"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Products"
pre = "#"
url = "products"
weight = 3
[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 4
[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 5
[params]
author = "Themefisher"
contact_info = "We <br>Work <br>Remotely."
description = "This is meta description"
logo = ""
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://goo.gl/maps/TuuJnN5kDr2WpKLy9"
map_center_lat = ""
map_center_lng = ""
map_marker = "images/map-marker.png"
map_position_lat = ""
map_position_lng = ""
[[params.social]]
icon = "fa-envelope-o"
link = "mailto:services.tinkerlook@gmail.com"
title = "Gmail"
[[params.social]]
icon = "fa-phone"
link = "tel:+2349034417900"
title = "phone"
